---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  namespace: dev
spec:
  selector:
    matchLabels:
      app: sample-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: sample-deployment
    spec:
      containers:
      - name: pods-sample-deployment
        image: tntaksreg.azurecr.io/sample:latest
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
    name: sample-service
    namespace: dev
spec:
  selector:
    app: sample-deployment
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sample-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: sample.e46708b92c054086909b.eastus.aksapp.io
    http:
      paths:
      - backend:
          serviceName: sample-service
          servicePort: 80
        path: /
