---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-deployment
  namespace: dev
spec:
  selector:
    matchLabels:
      app: monitor-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: monitor-deployment
    spec:
      containers:
      - name: pods-monitor-deployment
        image: docker.io/prom/prometheus
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
    name: monitor-service
    namespace: dev
spec:
  selector:
    app: monitor-deployment
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: monitor-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: monitor.e46708b92c054086909b.eastus.aksapp.io
    http:
      paths:
      - backend:
          serviceName: monitor-service
          servicePort: 80
        path: /
