---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
spec:
  selector:
    matchLabels:
      app: sample-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-deployment
    spec:
      containers:
      - name: pods-sample-deployment
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
    name: sample-service
spec:
  selector:
    app: sample-deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sample-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: sample-service
    servicePort: 80
  rules:
  - host: sample-service
    http:
      paths:
      - path: /
        backend:
          serviceName: sample-service
          servicePort: 80
